// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtxevhxjuwidackflppo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0eGV2aHhqdXdpZGFja2ZscHBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNDg5OTcsImV4cCI6MjA2NzcyNDk5N30.pnasEv4KdDnokXB_H8HWUZOecP_DWINeQVSLFVMW2oI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});